<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="2" failures="2" errors="0" time="2.766">
  <testsuite name="sample.test.js" errors="0" failures="2" skipped="0" timestamp="2022-09-02T06:29:37" time="2.053" tests="2">
    <testcase classname="App" name="Upload an image" time="0.062">
      <failure>Error: expect(jest.fn()).toHaveBeenCalledTimes(expected)

Expected number of calls: 1
Received number of calls: 0
    at _callee$ (D:\Projects\Intern\ImageUploadSkeleton\frontend\sample.test.js:65:24)
    at tryCatch (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (&lt;anonymous&gt;)
    at Object.&lt;anonymous&gt; (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.asyncJestTest (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
    at D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\jest-jasmine2\build\queueRunner.js:45:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
    at D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\jest-jasmine2\build\queueRunner.js:75:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)</failure>
    </testcase>
    <testcase classname="App" name="Get all image" time="0.008">
      <failure>Error: expect(jest.fn()).toHaveBeenCalledTimes(expected)

Expected number of calls: 1
Received number of calls: 0
    at _callee3$ (D:\Projects\Intern\ImageUploadSkeleton\frontend\sample.test.js:87:23)
    at tryCatch (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Projects\Intern\ImageUploadSkeleton\frontend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)</failure>
    </testcase>
  </testsuite>
</testsuites>